### PR TITLE
[semver:minor] Setup Cargo environment in $BASH_ENV

### PR DESCRIPTION
**Pull request by abernix**
Ensure that the Cargo environment is installed into CircleCI's [$BASH_ENV]
so later `run` steps which use `cargo` commands will have it in their path.

This isn't normally necessary since the Rust installer does add `source`
instructions into the "known" shell initialization scripts (e.g., `.bashrc`,
`.zshrc`, etc.), but since CircleCI necessitates using a special file at
a path specified in the environment by `$BASH_ENV`, this isn't handled
automatically.

I would be happy to believe that I'm doing something wrong, but I found it
necessary to do this in order to allow subsequent shells to invoke `cargo`
(or `rustc`, etc.) commands if I did not make this adjustment to `$BASH_ENV`.

See an example here in https://github.com/apollographql/federation/blob/df94502f81d617b8faa7c7f9efac711a3f76f760/.circleci/config.yml#L23-L26.

[$BASH_ENV]: https://circleci.com/docs/2.0/env-vars/#setting-an-environment-variable-in-a-shell-command

### CODE REVIEW

**Comment by gmemstr** [comment]
Hm, interesting - I was under the impression this would happen automatically as well, but I think you are correct in this case. Good catch!

**Comment by abernix** [comment]
@gmemstr I've corrected the syntax error that I had in my PR (using `run` within `run`, instead of `command` within `run`). 😬   I think this should be good to go now, but it doesn't seem this repo is setup to run CI on commits from contributors, perhaps? (I think I finally saw the failing PR status since _you_ had merged in the `master` branch and were authorized).

Let me know if there's anything else I can do!

**Comment by abernix** [comment]
@gmemstr Anything I can do to help with this?

**Comment by gmemstr** [comment]
@abernix Very minor nitpick, I think we can drop the escape character from the name. Otherwise LGTM - I'll wait a bit before merging if you want to tweak that :)

**Comment by abernix** [comment]
@gmemstr Sure! / Done!

I was thinking that the predictability of the display name, rather than outputting the value might be desirable but honestly not sure if interpolation works in the `ñame` field anyway!

**Review by gmemstr — APPROVED** [review]

**Pull request merged**
